DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS client_status;

CREATE TABLE client_status (id bigint auto_increment PRIMARY KEY, name VARCHAR(255) NOT NULL);

INSERT INTO client_status VALUES(1,'Новый');

CREATE TABLE client (
   ID  BIGINT AUTO_INCREMENT PRIMARY KEY,
   CREATED_ON  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   UPDATED_ON  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   first_name  VARCHAR(255),
   last_name  VARCHAR(255),
   phone_code VARCHAR(10),
   phone VARCHAR(10),
   EMAIL VARCHAR(255),
   STATUS_ID BIGINT NOT NULL
);

INSERT INTO client VALUES(1,CURRENT_TIMESTAMP,null,'Иван','Иванов','+7','9041869263','email@mm.ru',1)