CREATE TABLE ACCESS_OBJECT
(
    ID  BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME  VARCHAR(255) UNIQUE
);

CREATE TABLE ROLE_ACCESS_OBJECT
(
ROLE_ID BIGINT NOT NULL,
ACCESS_OBJECT_ID BIGINT NOT NULL
);

INSERT INTO ACCESS_OBJECT (NAME) VALUES ('SYS_ADMIN');