
CREATE TABLE USER
(
    ID  BIGINT AUTO_INCREMENT PRIMARY KEY,
    CREATED_ON  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_ON  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USERNAME VARCHAR(255) UNIQUE,
    PASSWORD VARCHAR(255),
    IS_ENABLED BOOLEAN
);

INSERT INTO USER VALUES(1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'SYSTEM','password',true);
INSERT INTO USER_IN_ROLE(USER_ID,ROLE_ID) VALUES(1,1);

INSERT INTO ACCESS_OBJECT (NAME) VALUES ('CLIENT_R'),('CLIENT_RE'),('CLIENT_RED');
